version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "install require library"
      - set
      - apt-get install git
      - apt-get install expect
      - pip install awscli --upgrade --user
      - pip install git-remote-codecommit
      # - bash build-scripts/git-clone.sh
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "build"
      # - cd manual-management
      - pwd
      - ls
      - bash build-scripts/git-push.sh
